IF(SPLINEGUI_INCLUDES AND SPLINEGUI_LIBRARIES)
  SET(SPLINEGUI_FIND_QUIETLY TRUE)
ENDIF(SPLINEGUI_INCLUDES AND SPLINEGUI_LIBRARIES)

FIND_PATH(SPLINEGUI_INCLUDES
          NAMES
          ActiveObject.h
          PATHS
          $ENV{HOME}/include
          PATH_SUFFIXES SplineGUI)

FIND_LIBRARY(SPLINEGUI_LIBRARIES 
             SplineGUI
             PATHS
             $ENV{HOME}/lib)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SPLINEGUI DEFAULT_MSG
                                  SPLINEGUI_INCLUDES SPLINEGUI_LIBRARIES)

MARK_AS_ADVANCED(SPLINEGUI_INCLUDES SPLINEGUI_LIBRARIES)
